### ISSUE TITLE
Thud for DART-6UL

### ISSUE THREAD

**Issue by embeddman** [varigit/variscite-bsp-platform#1]
Hello! Can I use yocto thud for DART6-UL?

**Comment by eranmati** [comment]
We will have an official release soon, and we will update http://variwiki.com/index.php?title=DART-6UL accordingly.
However, you can start using it now if you want.
Just note that we plan to upgrade the WiFi firmware before the official release.

Next time, please ask your questions in the Variscite customer portal:
https://varisciteportal.axosoft.com

Regards,
Eran

**Comment by eranmati** [comment]
The WiFi firmware is now updated.
