### ISSUE TITLE
No Yocto Dunfell release for VAR-SOM-MX8M-PLUS 

### ISSUE THREAD

**Issue by matthewmummert5** [varigit/variscite-bsp-platform#10]
Hi,

It looks like you skipped Dunfell for the VAR-SOM-MX8M-PLUS. You went from Zeus straight to Gatesgarth and Hardknott.

https://variwiki.com/index.php?title=VAR-SOM-MX8M-PLUS

But, you didn't skip Dunfell for the DART-MX8M-MINI

https://variwiki.com/index.php?title=DART-MX8M-MINI

Is a Dunfell release for the PLUS in the works? I'm asking because it seems a bit odd that Dunfell was skipped. I need Dunfell specifically and will develop it myself, if necessary.

**Comment by nsdrude** [comment]
@matthewmummert5 since the i.MX8M Plus is a new SoC, we followed NXP's official releases, and NXP did not release Yocto Dunfell.

**Comment by matthewmummert5** [comment]
Thank you for taking the time out of your busy day to respond to my question.
