### ISSUE TITLE
codeaurora.org downloads broken

### ISSUE THREAD

**Issue by joelsand** [varigit/variscite-bsp-platform#17]
Hi there!

According to https://bye.codeaurora.org/, it's shutdown as of today so downloads that reference source.codeaurora.org are failing (see example below).

~It looks like IMX has updated their recipes (e.g. https://github.com/Freescale/meta-freescale/commit/83b779a7ef69006564fb8d27e65c31917bc3b6f0).~ (not sure if that's relevant, looking closer). Any ETA on when the Variscite BSP file(s) will be updated?

Thanks,
Joel

```
ERROR: gstreamer1.0-plugins-good-1.20.0.imx-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'gitsm://source.codeaurora.org/external/mx8-fslc-linux/gstreamer1.0-plugins-good/1.20.0.imximx/gst-plugins-good.git;protocol=https;branch=MM_04.07.00_2205_L5.15.y')
```

**Comment by nsdrude** [comment]
@joelsand thanks for reporting this. This will be fixed in future releases.

For existing releases that face this problem, it can be fixed by adding `MIRRORS` to local.conf. Please see: https://variwiki.com/index.php?title=Yocto_Common_Errors#codeaurora.org_migration

**Comment by joelsand** [comment]
Thank you @nsdrude - that appears to be working!
