### ISSUE TITLE
Android 11.0.0_2.6.0 repo init broken due to manifest change

### ISSUE THREAD

**Issue by ngoslee-ttt** [varigit/variscite-bsp-platform#19]
var-imx-android-11.0.0_2.6.0.xml is missing: `<remote name="var-github" fetch="https://github.com/varigit/" review="" />`
It was removed during the codeaurora.org  changes.
11.0.0._2.2.0 also has the issue

Worked around it by editing the local copy at ~/var_imx-android-11.0.0_2.6.0/android_build/.repo/manifests

**Comment by hj2006** [comment]
@ngoslee-ttt  Thanks for reporting this. We have fixed this issue. 
Please see https://github.com/varigit/variscite-bsp-platform/commit/b8fee372683429f11e19ade0c7efb9535c908e22 simply resync the code it must work.

**Comment by hj2006** [comment]
Fixed the missing remote for varigit
