### ISSUE TITLE
Bitbake fails on warrior-fsl-4.19.35-mx8mm-v3.1 for image fsl-image-qt5

### ISSUE THREAD

**Issue by ahitchcelsee** [varigit/variscite-bsp-platform#2]
## Issue
Following the instructions on the [Variscite wiki](http://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_WARRIOR_V3.1_DART-MX8M-MINI) and attempting to run bitbake with fsl-image-qt5 results in the following error:
```ERROR: Nothing RPROVIDES 'tensorflow-lite' (but /yocto_build/sources/meta-fsl-bsp-release/imx/meta-sdk/recipes-fsl/packagegroup/packagegroup-imx-ml.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'tensorflow-lite' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tensorflow-lite']
NOTE: Runtime target 'packagegroup-imx-ml' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-imx-ml', 'tensorflow-lite']
ERROR: Required build target 'fsl-image-qt5' has no buildable providers.
Missing or unbuildable dependency chain was: ['fsl-image-qt5', 'packagegroup-imx-ml', 'tensorflow-lite']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Build failed.
```
## To Reproduce
 - Begin with a clean install of Ubuntu
 - Follow the instructions on the [Variscite wiki](http://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_WARRIOR_V3.1_DART-MX8M-MINI), following the simplest path (no local.conf customization, etc.)
    - Use release tag `warrior-fsl-4.19.35-mx8mm-v3.1`
    - Use distro `fsl-imx-xwayland`
 - At the bitbake step, run `bitbake fsl-image-qt5`

**Comment by varigigi** [comment]
Hi ahitchcelsee,
thanks for reporting.
Please start from scratch and download the latest revision (not the tag) as reported here
http://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_WARRIOR_V3.1_DART-MX8M-MINI#Download_Yocto_Warrior_based_on_Freescale_Community_BSP
(Next time, please use the Variscite customer portal, though)

Best Regards,
Pier
