### ISSUE TITLE
meta-variscite-bsp-imx depends on inexistant and unsourced meta-fsl-bsp-release

### ISSUE THREAD

**Issue by valentinlageard** [varigit/variscite-bsp-platform#24]
On the mickledore branch, meta-variscite-bsp-imx depends on meta-fsl-bsp-release which is not referenced and sourced in the manifest. In addition, https://github.com/nxp-imx/meta-fsl-bsp-release seems abandoned and has no support for kernel with version beyond 4...

I guess the relevant layer has been moved somewhere but then which it is ? And layer.conf should be updated accordingly.

**Comment by nsdrude** [comment]
@valentinlageard actually, fsl-bsp-release is required by meta-imx/meta-bsp: https://github.com/nxp-imx/meta-imx/blob/mickledore-6.1.36-2.1.0/meta-bsp/conf/layer.conf#L8

Which is included in Variscite's bblayers.conf: 
- https://github.com/varigit-dev/meta-variscite-sdk-imx/blob/scarthgap_6.6.23-2.0.0_var01/scripts/var-setup-release.sh#L41
- https://github.com/nxp-imx/meta-imx/blob/mickledore-6.1.36-2.1.0/tools/imx-setup-release.sh#L161

**Comment by jadinm** [comment]
In case anyone else is as confused as I was, I suppose that you meant that the layer "fsl-bsp-release is ~~required by~~ defined at meta-imx/meta-bsp https://github.com/nxp-imx/meta-imx/blob/mickledore-6.1.36-2.1.0/meta-bsp/conf/layer.conf#L8" and that the repo linked in the initial post isn't used at all.

After running `./var-setup-release.sh` as described in the README.md (with a correct pair machine-distribution), the `conf/bblayers.conf` is correctly filled.
