### ISSUE TITLE
Bitbake fsl-image-qt5 failure ICU-64 checksum mismatch

### ISSUE THREAD

**Issue by mmader87** [varigit/variscite-bsp-platform#3]
Hello,

I am receiving the following errors when attempting to build fsl-image-qt5.

Followed the directions on the variscite wiki: https://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_ZEUS_V1.0_DART-MX8M-MINI

mmader@ubuntu:~/var-fsl-yocto/build_wayland$ bitbake fsl-image-qt5
WARNING: You have included the meta-virtualization layer, but 'virtualization' has not been enabled in your DISTRO_FEATURES. Some bbappend files may not take effect. See the meta-virtualization README for details on enabling virtualization support.
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 4214 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "imx8mm-var-dart"
DISTRO               = "fsl-imx-wayland"
DISTRO_VERSION       = "5.4-zeus"
TUNE_FEATURES        = "aarch64 cortexa53 crc crypto"
TARGET_FPU           = ""
meta                 
meta-poky            = "HEAD:0275e68b0576cdefc19718e4b1977044f9f43f48"
meta-oe              
meta-multimedia      
meta-python          = "HEAD:aad5b3d070cd8c58828b0975cf861d8ebc90f460"
meta-freescale       = "HEAD:0be39721cea6e04c589a419f4bb07fabd0da6704"
meta-freescale-3rdparty = "HEAD:aea3771baa77e74762358ceb673d407e36637e5f"
meta-freescale-distro = "HEAD:ca27d12e4964d1336e662bcc60184bbff526c857"
meta-bsp             
meta-sdk             
meta-ml              = "HEAD:435f5e984856a943986491fddd061734a0b9eba5"
meta-browser         = "HEAD:5f365ef0f842ba4651efe88787cf9c63bc8b6cb3"
meta-rust            = "HEAD:5cda04c7c2158fc982502ca1e7893f71e4ca1729"
meta-gnome           
meta-networking      
meta-filesystems     = "HEAD:aad5b3d070cd8c58828b0975cf861d8ebc90f460"
meta-qt5             = "HEAD:432ad2aa6c3a13253fefc909faba368851d21fb1"
meta-swupdate        = "HEAD:8ad6a75e1778cdda671b3d6aea2a9692613020ec"
meta-virtualization  = "HEAD:514ce5f6b240600f06b9956737be1e33900bacac"
meta-variscite-imx   = "HEAD:09de6c4de2830bad3916aa59007982ecb9da04b4"

Initialising tasks: 100% |#######################################| Time: 0:00:05
Sstate summary: Wanted 2676 Found 0 Missed 2676 Current 152 (0% match, 5% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
WARNING: icu-64.2-r0 do_fetch: Checksum mismatch for local file /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz
Cleaning and trying again.
WARNING: icu-64.2-r0 do_fetch: Renaming /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz to /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz_bad-checksum_25c7b3d08c026e673e52f4c7d49269bf
WARNING: icu-64.2-r0 do_fetch: Checksum failure encountered with download of http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz - will attempt other sources if available
ERROR: icu-64.2-r0 do_fetch: Fetcher failure for URL: 'http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz'. Checksum mismatch!
File: '/home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz' has md5 checksum 25c7b3d08c026e673e52f4c7d49269bf when a3d18213beec454e3cdec9a3116d6b05 was expected
File: '/home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz' has sha256 checksum 752e37da5d5d54b98e49f6020173a21445d2a33cb8c77d2dae106324bc16dc26 when 627d5d8478e6d96fc8c90fed4851239079a561a6a8b9e48b0892f24e82d31d6c was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "25c7b3d08c026e673e52f4c7d49269bf"
SRC_URI[sha256sum] = "752e37da5d5d54b98e49f6020173a21445d2a33cb8c77d2dae106324bc16dc26"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: icu-64.2-r0 do_fetch: Fetcher failure for URL: 'http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/mmader/var-fsl-yocto/build_wayland/tmp/work/aarch64-poky-linux/icu/64.2-r0/temp/log.do_fetch.119311
ERROR: Task (/home/mmader/var-fsl-yocto/sources/poky/meta/recipes-support/icu/icu_64.2.bb:do_fetch) failed with exit code '1'
WARNING: icu-native-64.2-r0 do_fetch: Checksum mismatch for local file /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz
Cleaning and trying again.
WARNING: icu-native-64.2-r0 do_fetch: Renaming /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz to /home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz_bad-checksum_55f3a2828ca5b197b43b515e47bdec4d
WARNING: icu-native-64.2-r0 do_fetch: Checksum failure encountered with download of http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz - will attempt other sources if available
ERROR: icu-native-64.2-r0 do_fetch: Fetcher failure for URL: 'http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz'. Checksum mismatch!
File: '/home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz' has md5 checksum 55f3a2828ca5b197b43b515e47bdec4d when a3d18213beec454e3cdec9a3116d6b05 was expected
File: '/home/mmader/var-fsl-yocto/downloads/icu4c-64_2-src.tgz' has sha256 checksum b73ccffe1233c861fed79edacd77d5eb243332c84bb6cc4f64120aea7019cf00 when 627d5d8478e6d96fc8c90fed4851239079a561a6a8b9e48b0892f24e82d31d6c was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "55f3a2828ca5b197b43b515e47bdec4d"
SRC_URI[sha256sum] = "b73ccffe1233c861fed79edacd77d5eb243332c84bb6cc4f64120aea7019cf00"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: icu-native-64.2-r0 do_fetch: Fetcher failure for URL: 'http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/mmader/var-fsl-yocto/build_wayland/tmp/work/x86_64-linux/icu-native/64.2-r0/temp/log.do_fetch.119310
ERROR: Task (virtual:native:/home/mmader/var-fsl-yocto/sources/poky/meta/recipes-support/icu/icu_64.2.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1087 tasks of which 1085 didn't need to be rerun and 2 failed.

Summary: 2 tasks failed:
  /home/mmader/var-fsl-yocto/sources/poky/meta/recipes-support/icu/icu_64.2.bb:do_fetch
  virtual:native:/home/mmader/var-fsl-yocto/sources/poky/meta/recipes-support/icu/icu_64.2.bb:do_fetch
Summary: There were 7 WARNING messages shown.
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.
mmader@ubuntu:~/var-fsl-yocto/build_wayland$

**Comment by varigigi** [comment]
Hi,
I can reproduce the warnings, but while checking the mirrors the file get actually downloaded from
   http://downloads.yoctoproject.org/mirror/sources/icu4c-64_2-src.tgz
so no error are visible.
There's the chance that you experienced problems when connecting to the mirror.
I'm now closing the issue.
Please for future support visit us (free of charge) at
   https://varisciteportal.axosoft.com/
Thanks
