### ISSUE TITLE
bitbake fails to build 'missing imx-boot'

### ISSUE THREAD

**Issue by BCABLian** [varigit/variscite-bsp-platform#7]
Hi, I am fairly new to working with Variscites products, I am developing an application that runs on the Dart-6UL SoM, and we need to do some re-configuring to the yocto image.  mostly minor device tree stuff, but I am currently trying to redirect the CLI output from UART1 to UART4 to accommodate a custom carrier board.  when I went to pull the newest release tag using variscites instructions on the wiki, I found that I am now no longer able to build using `bitbake fsl-image-gui.`  a few months ago, I think I started back in July or August on this project, I was able to follow along with the build instructions and not have any issues.  now when I follow those same instructions I am presented with: 

```
ERROR: Nothing PROVIDES 'imx-boot'
imx-boot was skipped: incompatible with machine imx6ul-var-dart (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'fsl-image-gui' has no buildable providers.
Missing or unbuildable dependency chain was: ['fsl-image-gui', 'virtual/kernel', 'imx-boot']
```

I saw that a commit to the release branch was made recently, and I would just like to open this up to make Variscites team aware that whatever is pulled from: 

```
$ repo init -u https://github.com/varigit/variscite-bsp-platform.git -b dunfell
$ repo sync -j4
```

does not seem to build with bitbake.  I rolled back to the previous release tag from sept 15th, and this would build, but I had some issues applying my patches.  thankfully I saved off an old copy of my VM and can fix the issues I am currently having, but I was not able to get a fresh build directory going with the latest release.

**Comment by nsdrude** [comment]
@BCABLian thank you for reporting this issue, and for the detailed description. I just pushed a patch to fix this:
https://github.com/varigit/meta-variscite-hab/commit/afeedcef0e248b6f8888236cb3a2e0c7176ddce5 and updated the manifest file to include the patch: https://github.com/varigit/variscite-bsp-platform/commit/f51602079430889a4d2a284e0f0e73812962e48e
