### ISSUE TITLE
build instructions break at 'sources/poky/meta/recipes-devtools/binutils/binutils_2.34.bb:do_compile'

### ISSUE THREAD

**Issue by BCABLian** [varigit/variscite-bsp-platform#8]
Hi, I haven't had enough time to look through this one very much, but attached is a printout from the terminal output.  But I started with a fresh build directory and went through the wiki page again to just do the plain build instructions for the fsl-image-gui build with no changes to the source.  I pulled from the latest release after your team patched the code from another bug I entered.  the only difference is the name of my working directory, which I don't think should affect the build procedure aside from me going to a different directory name. 

Thanks, 
BL
[bug.txt](https://github.com/varigit/variscite-bsp-platform/files/7382903/bug.txt)

**Comment by nsdrude** [comment]
Hi Brandon,

I just did a clean build with these commands and no errors:
```
$ mkdir ~/imx6ul-test && cd ~/imx6ul-test
$ repo init -u https://github.com/varigit/variscite-bsp-platform.git -b dunfell && repo sync -j4
$ MACHINE=imx6ul-var-dart DISTRO=fslc-x11 . setup-environment build_x11
$ bitbake fsl-image-gui
```
What are the specifications of your build machine? Perhaps bitbake ran out of memory and the linker failed. In general, you need 4GB / CPU Thread.

In the future please use Variscite's ticket system: https://varisciteportal.axosoft.com/

Thanks,
Nate

**Comment by BCABLian** [comment]
will do in the future.  these are the same commands I used that led to the build not completing.  ran an apt update and upgrade to make sure the dep pkgs were all set.  ran the build commands again and failed in the same spot.  

I am building on a machine with a 32 core cpu (threadripper 3790x) and 32GB of ram.  running Ubuntu in a VM with these as the configured virtual resources.  I just rolled back to the tag from 6/22 listed in the wiki's release notes and I am just about done building the image without any failures.  

Thanks, 
Brandon

**Comment by nsdrude** [comment]
With the 3790x (32C/64T), You only have 512MB/thread. It is recommended to have minimum 2GB/thread, or 4GB/thread when building fsl-image-qt5.

Please try reducing threads by using PARALLEL_MAKE and BB_NUMBER_THREADS, or reduce your VM 16 threads.

Regards
Nate

**Comment by david-sterling** [comment]
Hi Brandon,

I think Nate is right. Sometimes if you -c do_clean and do that recipe again alone the linker works, that usually is because not having enough memory per thread. Chromium-based webview is one of the most problematic for me. 

Best,

David

**Comment by nsdrude** [comment]
Hi Brandon,

I'm going to close this. If you need additional support, please use Variscite's ticket system: https://varisciteportal.axosoft.com/

Thanks,
Nate
