### ISSUE TITLE
Changes require in U-boot,Linux Kernel recipes for Implementing Secure boot

### ISSUE THREAD

**Issue by dpatil89** [varigit/variscite-bsp-platform#9]
Hi All,
I successfully completed activity of High assurance boot  as per steps mentioned in below link 
**https://variwiki.com/index.php?title=High_Assurance_Boot&release=RELEASE_DUNFELL_V1.2_VAR-SOM-MX7**
Now I want to create automate all steps mentioned in above link using yocto.
First I started with U-boot, and I enabled SECURE option in **mx7dvar_som_defconfig**  but I got following error

cp: cannot stat '/home/VARI_YOCTO_DUNFELL/var-fslc-yocto2/build_fb/tmp/work/imx7_var_som-fslc-linux-gnueabi/u-boot-variscite/1.0-r0/git/mx7dvar_som_defconfig/u-boot.img': No such file or directory

When i manually compiled kernel u-boot-ivt.img is created instead of u-boot.img. And cp didn't get this file in that folder.
What are changes required u-boot recipes so that instead of u-boot.img it will copy u-boot-ivt.img

**Comment by nsdrude** [comment]
@dpatil89 There is no reference from NXP or Variscite to automate secure boot for imx7. If you want to impliment it yourself, you can use [meta-variscite-hab](https://github.com/varigit/meta-variscite-hab/commits/kirkstone) as a reference, which supports Variscite's imx8/8x/8m family of SoMs.
